# SalesVision — Sales & Profitability Analytics System

## 1. Project Overview

This project analyzes retail sales data to identify business trends,
profitability patterns, customer behavior, and regional performance.

## 2. Business Objectives

- Analyze total sales and profit.
- Identify the most profitable product categories.
- Investigate loss-making products.
- Analyze regional sales performance.
- Study the relationship between discounts and profit.
- Understand customer segment performance.

## 3. Dataset Description

Dataset: Tableau Sample Superstore

Rows: 10,194
Columns: 21

Tools:
- Python
- Pandas
- NumPy
- Matplotlib
- Jupyter Lab

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
%pip install xlrd

Requirement already satisfied: xlrd in c:\users\rezaf\anaconda3\lib\site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df = pd.read_excel(r"C:\Users\rezaf\Project\SalesVision\data\raw\sample_-_superstore.xls")

In [4]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [5]:
df.shape

(10194, 21)

In [6]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(14)
memory usage: 1.6+ MB

In [8]:
df.describe()

,Row ID,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2025-04-29 11:48:25.002942720,2025-05-03 10:52:45.626839296,228.225854,3.791838,0.155385,28.673417
min,1.000000,2023-01-03 00:00:00,2023-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2549.250000,2024-05-14 00:00:00,2024-05-19 00:00:00,17.220000,2.000000,0.000000,1.760800
50%,5097.500000,2025-06-25 00:00:00,2025-06-28 00:00:00,53.910000,3.000000,0.200000,8.690000
75%,7645.750000,2026-05-14 00:00:00,2026-05-18 00:00:00,209.500000,5.000000,0.200000,29.297925
max,10194.000000,2026-12-30 00:00:00,2027-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,2942.898656,NaN,NaN,619.906839,2.228317,0.206249,232.465115

In [9]:
df.describe(include = "all")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
count,10194.000000,10194,10194,10194,10194,10194,10194,10194,10194,10194,...,10194.0,10194,10194,10194,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000
unique,NaN,5111,NaN,NaN,4,804,800,3,2,542,...,654.0,4,1862,3,17,1849,NaN,NaN,NaN,NaN
top,NaN,US-2026-100111,NaN,NaN,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,10035.0,West,FUR-FU-10004270,Office Supplies,Binders,Staples,NaN,NaN,NaN,NaN
freq,NaN,14,NaN,NaN,6120,41,41,5281,9994,915,...,263.0,3253,20,6128,1548,50,NaN,NaN,NaN,NaN
mean,5097.500000,NaN,2025-04-29 11:48:25.002942720,2025-05-03 10:52:45.626839296,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,228.225854,3.791838,0.155385,28.673417
min,1.000000,NaN,2023-01-03 00:00:00,2023-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000
25%,2549.250000,NaN,2024-05-14 00:00:00,2024-05-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,17.220000,2.000000,0.000000,1.760800
50%,5097.500000,NaN,2025-06-25 00:00:00,2025-06-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,53.910000,3.000000,0.200000,8.690000
75%,7645.750000,NaN,2026-05-14 00:00:00,2026-05-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,209.500000,5.000000,0.200000,29.297925
max,10194.000000,NaN,2026-12-30 00:00:00,2027-01-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.800000,8399.976000
std,2942.898656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,619.906839,2.228317,0.206249,232.465115

In [10]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10189,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [11]:
print("Column Names:")
print(df.columns.tolist())

Column Names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [12]:
print(df.dtypes)

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State/Province            object
Postal Code               object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

In [13]:
print(df.dtypes)

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State/Province            object
Postal Code               object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

In [14]:
missing_percentage = (
    df.isnull().sum() / len(df)
) * 100

print(missing_percentage.round(2))

Row ID            0.0
Order ID          0.0
Order Date        0.0
Ship Date         0.0
Ship Mode         0.0
Customer ID       0.0
Customer Name     0.0
Segment           0.0
Country/Region    0.0
City              0.0
State/Province    0.0
Postal Code       0.0
Region            0.0
Product ID        0.0
Category          0.0
Sub-Category      0.0
Product Name      0.0
Sales             0.0
Quantity          0.0
Discount          0.0
Profit            0.0
dtype: float64

In [15]:
duplicate_count = df.duplicated().sum()

print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 0

In [16]:
df.describe()

,Row ID,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2025-04-29 11:48:25.002942720,2025-05-03 10:52:45.626839296,228.225854,3.791838,0.155385,28.673417
min,1.000000,2023-01-03 00:00:00,2023-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2549.250000,2024-05-14 00:00:00,2024-05-19 00:00:00,17.220000,2.000000,0.000000,1.760800
50%,5097.500000,2025-06-25 00:00:00,2025-06-28 00:00:00,53.910000,3.000000,0.200000,8.690000
75%,7645.750000,2026-05-14 00:00:00,2026-05-18 00:00:00,209.500000,5.000000,0.200000,29.297925
max,10194.000000,2026-12-30 00:00:00,2027-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,2942.898656,NaN,NaN,619.906839,2.228317,0.206249,232.465115

In [17]:
df[
    ["Sales", "Quantity", "Discount", "Profit"]
].describe().round(2)

          Sales  Quantity  Discount    Profit
count  10194.00  10194.00  10194.00  10194.00
mean     228.23      3.79      0.16     28.67
std      619.91      2.23      0.21    232.47
min        0.44      1.00      0.00  -6599.98
25%       17.22      2.00      0.00      1.76
50%       53.91      3.00      0.20      8.69
75%      209.50      5.00      0.20     29.30
max    22638.48     14.00      0.80   8399.98

In [18]:
categorical_columns = [
    "Category",
    "Sub-Category",
    "Region",
    "Segment",
    "Ship Mode"
]

for column in categorical_columns:
    print(f"\n{column}")
    print(df[column].unique())

Category
['Office Supplies' 'Furniture' 'Technology']

Sub-Category
['Paper' 'Binders' 'Labels' 'Storage' 'Art' 'Chairs' 'Fasteners' 'Phones'
 'Furnishings' 'Accessories' 'Bookcases' 'Envelopes' 'Appliances' 'Tables'
 'Supplies' 'Machines' 'Copiers']

Region
['Central' 'East' 'South' 'West']

Segment
['Consumer' 'Home Office' 'Corporate']

Ship Mode
['Standard Class' 'First Class' 'Second Class' 'Same Day']

In [19]:
print("Category Counts:")
print(df["Category"].value_counts())

print("\nRegion Counts:")
print(df["Region"].value_counts())

print("\nSegment Counts:")
print(df["Segment"].value_counts())

Category Counts:
Category
Office Supplies    6128
Furniture          2201
Technology         1865
Name: count, dtype: int64

Region Counts:
Region
West       3253
East       2986
Central    2335
South      1620
Name: count, dtype: int64

Segment Counts:
Segment
Consumer       5281
Corporate      3090
Home Office    1823
Name: count, dtype: int64

In [20]:
print(
    "Earliest Order Date:",
    df["Order Date"].min()
)

print(
    "Latest Order Date:",
    df["Order Date"].max()
)

print(
    "Earliest Ship Date:",
    df["Ship Date"].min()
)

print(
    "Latest Ship Date:",
    df["Ship Date"].max()
)

Earliest Order Date: 2023-01-03 00:00:00
Latest Order Date: 2026-12-30 00:00:00
Earliest Ship Date: 2023-01-07 00:00:00
Latest Ship Date: 2027-01-05 00:00:00

In [21]:
print(
    "Unique Orders:",
    df["Order ID"].nunique()
)

print(
    "Unique Customers:",
    df["Customer ID"].nunique()
)

print(
    "Unique Products:",
    df["Product ID"].nunique()
)

Unique Orders: 5111
Unique Customers: 804
Unique Products: 1862

In [23]:

# Check invalid values in numeric columns

print("Sales <= 0:", (df["Sales"] <= 0).sum())

print("Quantity <= 0:", (df["Quantity"] <= 0).sum())

print(
    "Invalid Discount:",
    ((df["Discount"] < 0) | (df["Discount"] > 1)).sum()
)

print("Missing Values:", df.isnull().sum().sum())

print("Duplicate Rows:", df.duplicated().sum())

Sales <= 0: 0
Quantity <= 0: 0
Invalid Discount: 0
Missing Values: 0
Duplicate Rows: 0

In [24]:

# Shipping date should not be earlier than order date

invalid_dates = df[
    df["Ship Date"] < df["Order Date"]
]

print("Invalid Date Records:", len(invalid_dates))

# Display invalid records if any
invalid_dates[
    ["Order ID", "Order Date", "Ship Date"]
].head(10)

Invalid Date Records: 0

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date]
Index: []

In [25]:
# Count records year-wise

yearly_records = (
    df["Order Date"]
    .dt.year
    .value_counts()
    .sort_index()
)

print(yearly_records)

Order Date
2023    2051
2024    2130
2025    2634
2026    3379
Name: count, dtype: int64

In [28]:

# Identify text columns

text_columns = df_clean.select_dtypes(
    include=["object", "string"]
).columns

print("Text Columns:")
print(text_columns.tolist())

Text Columns:
['Order ID', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name']

In [27]:

# Create a working copy of the original dataset

df_clean = df.copy()

print("Working copy created successfully!")
print("Dataset Shape:", df_clean.shape)

Working copy created successfully!
Dataset Shape: (10194, 21)

In [29]:

# Check leading and trailing spaces in text columns

for col in text_columns:
    spaces_count = (
        df_clean[col].astype("string").str.strip()
        .ne(df_clean[col].astype("string"))
        .sum()
    )

    print(f"{col}: {spaces_count} values with extra spaces")

Order ID: 0 values with extra spaces
Ship Mode: 0 values with extra spaces
Customer ID: 0 values with extra spaces
Customer Name: 0 values with extra spaces
Segment: 0 values with extra spaces
Country/Region: 0 values with extra spaces
City: 0 values with extra spaces
State/Province: 0 values with extra spaces
Postal Code: 0 values with extra spaces
Region: 0 values with extra spaces
Product ID: 0 values with extra spaces
Category: 0 values with extra spaces
Sub-Category: 0 values with extra spaces
Product Name: 0 values with extra spaces

In [30]:

# Check unique values in important categorical columns

categorical_columns = [
    "Category",
    "Sub-Category",
    "Segment",
    "Region",
    "Ship Mode"
]

for col in categorical_columns:
    print(f"\n{col}:")
    print(sorted(df_clean[col].dropna().unique()))

Category:
['Furniture', 'Office Supplies', 'Technology']

Sub-Category:
['Accessories', 'Appliances', 'Art', 'Binders', 'Bookcases', 'Chairs', 'Copiers', 'Envelopes', 'Fasteners', 'Furnishings', 'Labels', 'Machines', 'Paper', 'Phones', 'Storage', 'Supplies', 'Tables']

Segment:
['Consumer', 'Corporate', 'Home Office']

Region:
['Central', 'East', 'South', 'West']

Ship Mode:
['First Class', 'Same Day', 'Second Class', 'Standard Class']

In [32]:

# FINAL DATA QUALITY VALIDATION

print("========== SALESVISION DATA QUALITY REPORT ==========")

print("Dataset Shape:", df_clean.shape)

print("Missing Values:", df_clean.isnull().sum().sum())

print("Duplicate Rows:", df_clean.duplicated().sum())

print("Invalid Sales:", (df_clean["Sales"] <= 0).sum())

print("Invalid Quantity:", (df_clean["Quantity"] <= 0).sum())

print(
    "Invalid Discount:",
    (
        (df_clean["Discount"] < 0) |
        (df_clean["Discount"] > 1)
    ).sum()
)

print(
    "Invalid Shipping Dates:",
    (df_clean["Ship Date"] < df_clean["Order Date"]).sum()
)

print("Negative Profit Records:", (df_clean["Profit"] < 0).sum())

print("======================================================")

========== SALESVISION DATA QUALITY REPORT ==========
Dataset Shape: (10194, 21)
Missing Values: 0
Duplicate Rows: 0
Invalid Sales: 0
Invalid Quantity: 0
Invalid Discount: 0
Invalid Shipping Dates: 0
Negative Profit Records: 1901
======================================================

In [33]:

# Save the cleaned dataset

df_clean.to_csv(
    "salesvision_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

## File ka location check karne ke liye:

In [34]:
import os

print("File Location:", os.path.abspath("salesvision_cleaned.csv"))

File Location: C:\Users\rezaf\Project\SalesVision\notebooks\salesvision_cleaned.csv